language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm test
  - bash scripts/build.sh
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/deploy.sh; fi'
git:
  depth: false
